kind: pipeline
type: docker
name: autotag

trigger:
    branch:
        - main
    event:
        - push

steps:
    - name: Autotag
      image: ellerbrock/alpine-bash-git
      environment:
          GITHUB_TOKEN:
              from_secret: github_token
          GITHUB_USER:
              from_secret: github_user
      commands:
          - echo machine github.com login $GITHUB_USER password $GITHUB_TOKEN > ~/.netrc
          - git pull origin main
          - bash ./scripts/autotag.sh
          - git commit -m "bump tags [CI SKIP]"
          - git push --force --follow-tags origin main

---
kind: pipeline
type: docker
name: badge

depends_on:
    - autotag

steps:
    - name: Restore Cache
      image: plugins/s3-cache
      failure: ignore
      settings:
          pull: true
          restore: true
          root:
              from_secret: S3_DRONE_BUCKET_NAME
          endpoint:
              from_secret: S3_DRONE_ENDPOINT
          access_key:
              from_secret: S3_DRONE_ACCESS_KEY
          secret_key:
              from_secret: S3_DRONE_SECRET_KEY
          mount:
              - build/
              - bin/
              - dist/

    - name: Build Badges
      image: golang:latest
      environment:
          GOPATH: /build
          GOBIN: /build/bin
          GOCACHE: /build/cache
          ENDPOINT:
              from_secret: S3_DRONE_ENDPOINT
          ACCESS_KEY:
              from_secret: S3_DRONE_ACCESS_KEY
          SECRET_KEY:
              from_secret: S3_DRONE_SECRET_KEY
      commands:
          - mv -f build / || true
          - make build-badges-success
          - ./bin/mc alias set drone-ci $ENDPOINT $ACCESS_KEY $SECRET_KEY
          - ./bin/mc cp --recursive ./dist drone-ci/build-badges/tower
          - mv -f /build . || true

    - name: Save Cache
      image: plugins/s3-cache
      failure: ignore
      when:
          status: [success, failure]
      settings:
          rebuild: true
          root:
              from_secret: S3_DRONE_BUCKET_NAME
          endpoint:
              from_secret: S3_DRONE_ENDPOINT
          access_key:
              from_secret: S3_DRONE_ACCESS_KEY
          secret_key:
              from_secret: S3_DRONE_SECRET_KEY
          mount:
              - build/
              - bin/
              - dist/
      depends_on:
          - Build Badges

---
kind: pipeline
type: docker
name: test

trigger:
    event:
        - pull_request

steps:
    - name: Restore Cache
      image: plugins/s3-cache
      failure: ignore
      settings:
          pull: true
          restore: true
          root:
              from_secret: S3_DRONE_BUCKET_NAME
          endpoint:
              from_secret: S3_DRONE_ENDPOINT
          access_key:
              from_secret: S3_DRONE_ACCESS_KEY
          secret_key:
              from_secret: S3_DRONE_SECRET_KEY
          mount:
              - build/
              - dist/

    - name: Test
      image: golang:latest
      environment:
          GOPATH: /build
          GOBIN: /build/bin
          GOCACHE: /build/cache
      commands:
          - mv -f build / || true
          - (make test-ci)
          - export TEST_EXIT_CODE=$?
          - mv -f /build . || true
          - exit $TEST_EXIT_CODE

    - name: Save Cache
      image: plugins/s3-cache
      failure: ignore
      when:
          status: [success, failure]
      settings:
          rebuild: true
          root:
              from_secret: S3_DRONE_BUCKET_NAME
          endpoint:
              from_secret: S3_DRONE_ENDPOINT
          access_key:
              from_secret: S3_DRONE_ACCESS_KEY
          secret_key:
              from_secret: S3_DRONE_SECRET_KEY
          mount:
              - build/
      depends_on:
          - Test

    - name: Flush Cache
      image: plugins/s3-cache
      failure: ignore
      when:
          status: [success, failure]
      settings:
          flush: true
          root:
              from_secret: S3_DRONE_BUCKET_NAME
          endpoint:
              from_secret: S3_DRONE_ENDPOINT
          access_key:
              from_secret: S3_DRONE_ACCESS_KEY
          secret_key:
              from_secret: S3_DRONE_SECRET_KEY
          mount:
              - build/
      depends_on:
          - Test

    - name: Discord Notification - Success
      image: appleboy/drone-discord
      failure: ignore
      when:
          status: [success]
      settings:
          username: Tower - Test Passed
          webhook_id:
              from_secret: DISCORD_WEBHOOK_ID
          webhook_token:
              from_secret: DISCORD_WEBHOOK_TOKEN
      depends_on:
          - Test

    - name: Discord Notification - Failure
      image: appleboy/drone-discord
      failure: ignore
      when:
          status: [failure]
      settings:
          username: Tower - Test Failed
          webhook_id:
              from_secret: DISCORD_WEBHOOK_ID
          webhook_token:
              from_secret: DISCORD_WEBHOOK_TOKEN
      depends_on:
          - Test
