kind: pipeline
type: docker
name: test-code

steps:
  - name: Restore Cache
    image: plugins/s3-cache
    settings:
      pull: true
      restore: true
      root:
        from_secret: S3_DRONE_BUCKET_NAME
      endpoint:
        from_secret: S3_DRONE_ENDPOINT
      access_key:
        from_secret: S3_DRONE_ACCESS_KEY
      secret_key:
        from_secret: S3_DRONE_SECRET_KEY
      mount:
        - build/
        - bin/
        - dist/

  - name: Test
    image: golang:latest
    environment:
      GOPATH: /build
      GOBIN: /build/bin
      GOCACHE: /build/cache
    commands:
      - mv build / || true
      - (make test-ci)
      - export TEST_EXIT_CODE=$?
      - mv /build . || true
      - exit $TEST_EXIT_CODE

  - name: Build Badges
    image: golang:latest
    failure: ignore
    when:
      status: [ success ]
    environment:
      BUCKET_name:
        from_secret: S3_DRONE_BUCKET_BADGE
      ENDPOINT:
        from_secret: S3_DRONE_ENDPOINT
      ACCESS_KEY:
        from_secret: S3_DRONE_ACCESS_KEY
      SECRET_KEY:
        from_secret: S3_DRONE_SECRET_KEY
    commands:
      - make build-badges
      - ./bin/mc alias set drone-ci $ENDPOINT $ACCESS_KEY $SECRET_KEY
      - ./bin/mc cp ./dist/* drone-ci/$BUCKET_NAME/tower


  - name: Save Cache
    image: plugins/s3-cache
    when:
      status: [ success, failure ]
    settings:
      rebuild: true
      root:
        from_secret: S3_DRONE_BUCKET_NAME
      endpoint:
        from_secret: S3_DRONE_ENDPOINT
      access_key:
        from_secret: S3_DRONE_ACCESS_KEY
      secret_key:
        from_secret: S3_DRONE_SECRET_KEY
      mount:
        - build/
        - bin/
        - dist/

  - name: Flush Cache
    image: plugins/s3-cache
    when:
      status: [ success, failure ]
    settings:
      flush: true
      flush_age: 7
      root:
        from_secret: S3_DRONE_BUCKET_NAME
      endpoint:
        from_secret: S3_DRONE_ENDPOINT
      access_key:
        from_secret: S3_DRONE_ACCESS_KEY
      secret_key:
        from_secret: S3_DRONE_SECRET_KEY
      mount:
        - build/
        - bin/
        - dist/

  - name: Discord Notification - Success
    image: appleboy/drone-discord
    when:
      status: [ success ]
    settings:
      username: Tower Drone - Test Passed
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN

  - name: Discord Notification - Failure
    image: appleboy/drone-discord
    when:
      status: [ failure ]
    settings:
      username: Tower Drone - Test Failed
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
